# File di esempio. I colleghi devono copiare questo file,
# rinominarlo in config.properties e inserire le proprie credenziali locali.
db.url=jdbc:mysql://localhost:3306/smart_mobility
db.user=inserisci_il_tuo_utente_qui
db.password=inserisci_la_tua_password_qui