package backend;

import java.io.IOException;
import java.io.OutputStream;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;

/**
 * Controller per la gestione dell'endpoint GET /api/mezzo.
 */
public class MezzoController implements HttpHandler {
    
    private MezzoManager mezzoManager;

    public MezzoController() {
        this.mezzoManager = new MezzoManager();
    }

    @Override
    public void handle(HttpExchange exchange) throws IOException {
        // Imposta le intestazioni CORS
        exchange.getResponseHeaders().add("Access-Control-Allow-Origin", "*");
        exchange.getResponseHeaders().add("Access-Control-Allow-Methods", "GET, OPTIONS");
        exchange.getResponseHeaders().add("Access-Control-Allow-Headers", "Content-Type, Authorization");

        if ("OPTIONS".equalsIgnoreCase(exchange.getRequestMethod())) {
            exchange.sendResponseHeaders(204, -1);
            return;
        }

        if ("GET".equalsIgnoreCase(exchange.getRequestMethod())) {
            // Validazione token di sessione
            String authHeader = exchange.getRequestHeaders().getFirst("Authorization");
            if (authHeader == null || !authHeader.startsWith("Bearer ")) {
                sendResponse(exchange, 401, "{\"errore\": \"Non autorizzato: token mancante\"}");
                return;
            }
            
            String token = authHeader.substring(7);
            Integer idUtente = SessionManager.getInstance().getUserIdByToken(token);
            if (idUtente == null) {
                sendResponse(exchange, 401, "{\"errore\": \"Non autorizzato: token non valido o scaduto\"}");
                return;
            }

            // Recupera idMezzo dalla query string
            String query = exchange.getRequestURI().getQuery();
            if (query == null || !query.contains("idMezzo=")) {
                sendResponse(exchange, 400, "{\"errore\": \"Richiesta non valida: idMezzo mancante\"}");
                return;
            }

            int idMezzo = -1;
            try {
                String idStr = query.split("idMezzo=")[1].split("&")[0];
                idMezzo = Integer.parseInt(idStr);
            } catch (Exception e) {
                sendResponse(exchange, 400, "{\"errore\": \"Richiesta non valida: idMezzo formato errato\"}");
                return;
            }

            // Recupero dati e calcolo
            Mezzo mezzo = mezzoManager.getMezzo(idMezzo);
            if (mezzo == null) {
                sendResponse(exchange, 404, "{\"errore\": \"Mezzo non trovato\"}");
                return;
            }

            double distanzaStimata = mezzoManager.calcolaDistanzaStimata(mezzo);

            // Costruisci JSON di risposta
            String jsonResponse = String.format(
                "{\"idMezzo\": %d, \"tipologia\": \"%s\", \"portataMassima\": %.2f, \"livelloBatteria\": %.2f, \"distanzaStimata\": %.2f}",
                mezzo.getIdMezzo(),
                mezzo.getTipologia(),
                mezzo.getPortataMassima(),
                mezzo.getLivelloBatteria(),
                distanzaStimata
            );
            // Convert to valid JSON format (dot for decimals instead of comma depending on Locale)
            jsonResponse = jsonResponse.replace(',', '.'); // Fix comma generated by %f in some locales if any, but better approach is below
            
            String jsonRes = "{" +
                "\"idMezzo\":" + mezzo.getIdMezzo() + "," +
                "\"tipologia\":\"" + mezzo.getTipologia() + "\"," +
                "\"portataMassima\":" + mezzo.getPortataMassima() + "," +
                "\"livelloBatteria\":" + mezzo.getLivelloBatteria() + "," +
                "\"distanzaStimata\":" + distanzaStimata +
            "}";

            exchange.getResponseHeaders().add("Content-Type", "application/json");
            sendResponse(exchange, 200, jsonRes);
        } else {
            sendResponse(exchange, 405, "{\"errore\": \"Metodo non consentito\"}");
        }
    }

    private void sendResponse(HttpExchange exchange, int statusCode, String response) throws IOException {
        byte[] bytes = response.getBytes("UTF-8");
        exchange.sendResponseHeaders(statusCode, bytes.length);
        try (OutputStream os = exchange.getResponseBody()) {
            os.write(bytes);
        }
    }
}
